// Auto-generated by backend/ml/train_esp32_model.py on 2026-09-01T16:36:27.289612Z
// Source: Smart-Agriculture 10K + 5-class agronomic remap
// Features: ['ph', 'temperature', 'moisture', 'ec']

int classify(float ph, float temperature, float moisture, float ec) {
  if (ec <= 3.9000f) {
    if (temperature <= 27.8000f) {
      if (ec <= 3.5000f) {
        return 0;
      } else {
        if (moisture <= 68.8529f) {
          return 2;
        } else {
          if (moisture <= 70.0000f) {
            return 2;
          } else {
            return 0;
          }
        }
      }
    } else {
      if (ec <= 2.1000f) {
        if (moisture <= 68.4000f) {
          return 1;
        } else {
          if (moisture <= 70.0000f) {
            return 1;
          } else {
            return 0;
          }
        }
      } else {
        if (moisture <= 69.6000f) {
          return 2;
        } else {
          if (moisture <= 70.0000f) {
            return 2;
          } else {
            return 0;
          }
        }
      }
    }
  } else {
    if (moisture <= 70.8000f) {
      if (moisture <= 67.6000f) {
        return 3;
      } else {
        if (moisture <= 70.0000f) {
          return 3;
        } else {
          return 0;
        }
      }
    } else {
      return 0;
    }
  }

}
